### ISSUE TITLE
Possible Security Problems

### ISSUE THREAD

**Issue by ctindall** [EmotionCognitionLab/hrv-social#1]
Hey there! I noticed some possible problems in some code in this repo. A quick summary of a few of them is below, but let me know if you're interested in seeing a full report or talking about cloud security in general.

---

**severity:** serious

**filename:** `./server/setup/cf-update-stack.yaml`

**line number(s):** [192]

**resource(s):** 

IAM role should not allow * action on its permissions policy

---

**severity:** warning

**filename:** `./server/setup/cf-create-stack.yaml`

**line number(s):** [15]

**resource(s):** 

IAM role should not allow * resource on its permissions policy

---

**severity:** warning

**filename:** `./server/setup/cf-update-stack.yaml`

**line number(s):** [335, 349]

**resource(s):** 

IAM managed policy should not allow * resource

---

**severity:** warning

**filename:** `./server/setup/cf-update-stack.yaml`

**line number(s):** [87, 192]

**resource(s):** 

IAM role should not allow * resource on its permissions policy

---

**severity:** warning

**filename:** `./server/setup/cf-update-stack.yaml`

**line number(s):** [222, 241, 259, 335, 349]

**resource(s):** 

Resource found with an explicit name, this disallows updates that require replacement of this resource

**Comment by noah10** [comment]
Cameron - Given that you opened similar issues in 28 repos in a short time, I'm assuming that you're using a bot to promote your services. Unfortunately your bot has flagged legitimate configurations as security issues. In the future I'd recommend that you manually review the bot output before opening the issues.
